# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.PositiveIntegerField()),
                ('hotel', models.PositiveIntegerField()),
                ('restaurent', models.PositiveIntegerField()),
                ('shopping', models.PositiveIntegerField()),
                ('sport', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='user',
        ),
        migrations.RemoveField(
            model_name='restaurent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shopping',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='user',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Restaurent',
        ),
        migrations.DeleteModel(
            name='Shopping',
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
    ]
