# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amount', '0002_auto_20170713_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='spent',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='amount.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spent',
            name='hotel',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='spent',
            name='movie',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='spent',
            name='restaurent',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='spent',
            name='shopping',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='spent',
            name='sport',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
