# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amount', '0003_auto_20170713_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spent',
            name='user',
        ),
        migrations.AddField(
            model_name='spent',
            name='name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
